language: ruby
sudo: false
script: chmod +x sync.sh && ./sync.sh
addons:
  apt:
    packages:
    - graphviz
env:
  global:
  - secure: VVsbFVa2XOSlQm/e5KjJbtFMeAw0yCP5wTlAyhIIy1+XXmYcZOcMrde6r+1WG1dNaJ/pho14NYaP7i1Il4abeJrZPiAGecEWaGpo0vk+T+Db2NT/nqL2ItmVgXmtPGWav+SXpQc1JQVBGIjPsJwlxYr7l5tFTVcf296I8D5Db2gqWfBq5F/5YjtqyJ/i7qoE0FnqCtc8t6aZlgQEgEjO3PUBKwvmCASX4U7Qm4cmLNteDoXLf+gRVwSH6Ne3JgQFLAU4tH+XGpbvE8cGxFnnFPErCbU9VELblQlXyvhYrveHq87B2bBhio0IPRQhToI/whvk8lxRqX1zCfXlkCrYvBNMv30zWL23hr54Tc9jFAyVoRulwIv1naTd8xMSHjkGv0Zi7apfsjG7AOLBTRc/VBI9KUSBQrUkVhbwDuSYJQymnhQ6AH12nwSwId6KQQKaWYCPeiwxQ/FMPaLc43gwBi2hISuPPAONPMK1D830R0IoZsrCLtndKhgcZmx9wGUv0zNjdDBHuxm/7dwGmfiANu2LRwClj85BoTuE8k9sf+xpWWAjfndbDWtmSN1uVR7c8MAuOg+PoJu3+QnuBW+QgXO3h2fBF6WyU76v6KKMDcZx072b7CENfJaIkuBfUorbngOWQk49cqukJyG1JWu8gmp3FcNGqSngJhk/I9cQUdI=
