# JS에서 비동기 프로그래밍
Jisung, Ahn <narusas.gmail.com>
v1.0, 2018-03-28
:showtitle:
:page-navtitle: JS에서 비동기 프로그래밍
:page-description: JS에서 비동기 프로그래밍에 대해 이야기합니다. 
:page-root: ../../../


## Single Thread
javascript는 언어적 차원에서 단일 쓰래드만 지원합니다. 우리가 작성한 코드는 단 한줄만이 실행중인 상태입니다.  단 하나의 쓰래드에 의해서 말이죠. 

[source,javascript]
----
var a = 10;
var b = 20;

function swap(){
    var swap = a;
    a = b;    
    b = swap;
}
----

따라서 다른 언어와 달리 JS에서는 위의 코드에서 동시성 문제가 발생하지 않습니다. a와 b 변수에 동시에 접근하여 변경 하는 경우자체가 발생하지 않으니까요. 

NOTE: 네 최근에는 조금 달라졌습니다. ServiceWorker가 등장하며 제한적이나마 멀티 쓰래딩이 가능해졌습니다. 

언어 차원에서 단일 쓰래드로 정의했기 때문에 동시성 문제를 배제하고 프로그래밍 할수 있다는 것은 나쁘지 않습니다만, 이제 성능이 문제가 됩니다. 


## Performance
[source, javascript]
----
function f(){
  var text = fileUtil.readFile('a.txt');
  return parseCsv(text);
}
----

만약 a.txt의 용량이 커서 읽는데 시간이 많이 걸리면 어떻게 될까요? 사실 배치(batch) 작업에서는 크게 문제 되지 않습니다. 그냥 순서대로 실행하면 되니까요. 우리가 bash 쉘 스크립트같은 곳에서 동시성을 요구하지 않는것과 비슷합니다. 순서대로 일련의 작업을 잘 실행해주면됩니다. 

하지만 JS의 대부분은 웹 브라우저에서 동작합니다. (네 node express  잘 알고 있습니다)

웹 브라우저에서 사용자가 원하는 것은 배치 작업이 아닙니다. 사용자가 클릭하고, 편집하고, 스크롤하고, 저장하고...

동시에 많은 작업을 수행하기를 원할수 있습니다.  하지만, 동시에 시간이 걸리는 작업도 수행해야 합니다. 

이 두가지를 동시에 요청하면 JS로는 답이 나오지 않습니다.  

[source, javascript]
----
function click1(){
  var text = fileUtil.readFile('a.txt');
  return parseCsv(text);
}

function click2() {
  var text = fileUtil.readFile('b.txt');
  return parseCsv(text);
}
----

사용자가 버튼을 클릭하여 click1이 수행중인데 용량이 커서 읽어오는데 10초쯤 걸립니다. 그런데 또다른 버튼을 클릭해 click2 를 실행하려고 해도 click1이 실행중이기 때문에 click2는 10초후에 실행될 겁니다. 
순차적으로 시간을 소비하여 수행해야 하니까요. 


## Asynchronous

따라서 JS가 아닌 다른 수단이 필요해집니다.  JS자체로는 이문제를 해결할수 없습니다. 그래서 js의 실행환경을 제공하는 주변 에서 기능을 제공하게 됩니다. 

웹브라우저에서는 XmlHttpRequest 을 제공합니다. js에서 xmlHttpRequest를 호출하면 웹브라우저는 이에 대한 실행을 C Posix 쓰래드로 실행합니다! JS 쓰래드가 아니고요. (웹브라우저의 구현 언어와 라이브러리에 따라 다른 언어와 쓰래드 라이브러리를 사용할겁니다)

[source, javascript]
----
var oReq = new XMLHttpRequest();
oReq.addEventListener("load", function callback(response){
    console.log('load'+response); // # <1>
});
oReq.open("GET", "http://www.example.org/example.txt");
oReq.send();  // # <2> 
console.log('sent!');  // # <3>
----
`<2>` send 함수를 호출한다고 해서 js가 동기적으로 응답이 올때까지 기다리지는 않습니다. 그냥 빨리 끝나는 함수 하나를 호출한 것 뿐입니다. 바로 `<3>` 으로 넘어가 실행합니다. 


그럼 `<1>` 은 언제 실행될까요?  

- JS 함수 `<1>` 을 임시로 저장해 둡니다. 
- C++로 만들어진 쓰래드가 HTTP 요청을 실행하여 서버에 요청을 보내고, 
- 응답이 와서 응답 데이터를 C++로 파싱이 한후에 저장해 둡니다. 
- 임시로 저장했던 JS 함수 `<1>` 을 micro task queue에 추가 합니다. 
- JS의 유일한 쓰래드가 현재 실행중인 macro task(사용자의 클릭이나 document load같은 주요 이벤트에 대해 실행되는) 코드가 없을때
- JS의 유일한 쓰래드를  macro task queue를 실행하게 합니다. 
- JS 쓰래드는 micro task queue에 저장되어 있던 `<1>` 함수를 데이터와 함께 호출합니다 

이런 콜백 기반의 비동기화 방식은 다음과 같은 전제를 합니다. 

* CPU는 빠르다.
* IO는 느리다. 
* 따라서 IO는 JS에서 하지말고, CPU에 관련된 것만 JS로 하자. 

여전히 JS는 단일 쓰래드입니다.  CPU를 많이 소비하는 작업을 하면 여전히 느려집니다. 
하지만 IO 때문에 느려지는것은 회피할수 있게 되었습니다.  

웹브라우저상에서 이런식으로 사용할수 있는 비동기 콜백은 과거에는 setTimeout, XmlHttpRequest 정도 였습니다. 

과거에도 setTimeout을 통해 micro task들을 사용하기는 했습니다.

[source, javascript]
----
function click1() {
  setTimeout(function() {
    doSomething();
  },0); // # <1>
}
----
<1> timeout 시간을 0으로 주었습니다. 이를 통해 현재 실행중인 macro task가 종료된후에 바로 이어서 micro task를 수행할수 있게 됩니다. 

이런 코드를 통해 현재 macro task가 빠르게 종료시키고, 혹시 다른 클릭등 또다른 macro task가 있으면 그쪽을 우선적으로 실행하여 사용자의 요청에 반응하게 하고, 그후에 시간이 걸리는 작업을 수행하게 할수 있었습니다. 이 과정에서  active object 패턴을 사용 할 수도 있었죠. 

하지만 ES5를 거치면서 Promise가 추가 되었습니다. 이를 통해 micro task queue를 더 적극적으로 사용할수 있게 되었습니다. 

## Promise
개념적으로 Promise는 micro task의 선언입니다. 생성자로 준 함수는 바로 micro task queue에 추가됩니다. 

[source, javascript]
----
new Promise(function(){
  console.log("Here");
});
console.log("Out here");
----

위의 코드를 실행시키면 다음처럼 실행됩니다. 

[source]
----
Out here # <1>
Here # <2>
----
<1> macro task에서 실행되었음 
<2> micro task에서 실행되었음

여기에서 아 그런가 보다 하고 넘어가기가 쉽습니다만..

만약 코드가 다음처럼 무한 루프에 빠진다면 micro task는 실행되지 않습니다. 

[source, javascript]
----
new Promise(function(){
  console.log("Here");
});
console.log("Out here");
let i=0;
for(true) {
  i = i+1;
}
----
[source]
----
Out here # <1>
----
<1> macro task에서 실행되었음 

왜냐하면 JS의 유일한 쓰래드가 유휴상태가 되지 않았기 때문에, macro task가 종료되지 않았기 때문에 micro task를 실행할 쓰래드가 없기 때문입니다. 

이처럼 micro task의 실행에 있어 대전제는 JS의 유일한 쓰래드가 실행하는 다른 JS 코드가 없어야 합니다. 

## Promise.then

Promise.then은 새롭게 micro task를 추가하는 명령입니다. 

[source,javascript]
----
new Promise(resolve=>{
  resolve(10);
}).then(value=>{
  
}).catch(err=>{

});
----

Promise의 생성자에 넘긴 함수는 micro task에서 실행되어 다음에 실행될 함수를 지정합니다. 

* resolve 함수를 호출하면, then에 넘겨진 함수를 micro task에 추가합니다. 
* reject를 호출하면 catch에 넘겨진 함수를 micro task에 추가합니다. 

WARNING: 여기에서 중요한것은 다음에 어떤 함수를 호출할지는 오로지 resolve, reject를 호출할때만 결정된다는 것입니다. 만약 resolve, reject 두 함수중 아무것도 호출하지 안는다면 해당 Promise는 이상 상태로 남게 됩니다. 


then에 넘긴 함수가 micro task queue를 통해 실행된 결과로 promise를 반환할수 있습니다. 그럼 또 then을 반복할수 있습니다. 

[source,javascript]
----
new Promise( function(resolve, reject) {
  resolve(10);
}).then(value=>{
  return new Promise(function(resolve, reject) {
    resolve(value +10);
  });
}).then(nextValue => {
  console.log(nextValue);
})
.catch(err=>{

});
----

이렇게 then이 promise를 반환하는 경우에 한해 chaining을 할수 있습니다. 

## Async / Await




## Sequence diagram
Prmise를 Sequence diagram으로 표현하면 다음과 같겠지만, 적당히만 보시기 바랍니다. 정확한 그림은 아니니까요. 

[plantuml]
....
participant "JS Main Loop"
participant "Your Code"
participant "function 1"
participant "callback 1"
participant "function 2"
participant "callback 2"
participant "Promise 1"
participant "Promise 2"
participant "Promise TaskQue"

"JS Main Loop" -> "Your Code"
activate "Your Code"

create "function 1"
"Your Code" -> "function 1": create
create "callback 1"
"Your Code" -> "callback 1": create
create "Promise 1"
"Your Code" -> "Promise 1": new with function 1, then callback 1

"Promise 1" -> "Promise TaskQue": add
"Your Code" -> "Your Code": do something

create "function 2"
"Your Code" -> "function 2": create
create "callback 2"
"Your Code" -> "callback 2": create
create "Promise 2"
"Your Code" -> "Promise 2": new with function 2, then callback 2

"Promise 2" -> "Promise TaskQue": add
"Your Code" -> "Your Code": do something
"JS Main Loop" <- "Your Code"
deactivate "Your Code"

...

"JS Main Loop" -> "Promise TaskQue": next promise
"JS Main Loop" <- "Promise 1": return
"JS Main Loop" -> "Promise 1": execute
"Promise 1" -> "function 1": execute
activate "function 1"
"Promise 1" <- "function 1": resolve
deactivate "function 1"
"Promise 1" -> "Promise 1": fulfilled

...

"JS Main Loop" -> "Promise TaskQue": next promise
"JS Main Loop" <- "Promise 2": return
"JS Main Loop" -> "Promise 2": execute

"Promise 2" -> "function 2": execute
activate "function 2"
"Promise 2" <- "function 2": resolve
deactivate "function 2"
"Promise 2" -> "Promise 2": fulfilled

"JS Main Loop" -> "callback 1": execute
"JS Main Loop" -> "callback 2": execute
....



